export const countries: any = {
	USA: "united-states",
	NED: "netherlands",
	AUS: "australia",
	GBR: "united-kingdom",
	FRA: "france",
	MEX: "mexico",
	ESP: "spain",
	MON: "monaco",
	CAN: "canada",
	DEN: "denmark",
	JPN: "japan",
	THA: "thailand",
	CHN: "china",
	FIN: "finland",
};
